BEGIN;

DROP TABLE IF EXISTS "brand",
"product"



-- Création de la table "Brand"

CREATE TABLE "brand" (
  "codeBrand" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- Création de la table "Product"

CREATE TABLE "product" (
 "codeProduct" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" text NOT NULL,
  description text NOT NULL,
  "brand_codeBrand" integer NOT NULL REFERENCES "brand"("codeBrand"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

COMMIT;